[package]
name = "win_saved"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.5"
openzeppelin = "0.17.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.35.1" }

[[target.starknet-contract]]
casm = true
sierra = true

[scripts]
test = "snforge test"

[tool.fmt]
max_line_length = 100
tab_width = 4
